name: Terraform Deploy

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Init
    
      run: terraform init

    - name: Terraform Validate
      
      run: terraform validate

    - name: Terraform Plan
      
      run: terraform plan -out=tfplan -input=false 

    - name: Terraform Apply
      
      run: terraform apply -input=false -auto-approve tfplan