name: Terraform Deploy

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
        ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
        ARM_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
        ARM_CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
        ARM_TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0
        
    - name: Terraform Format
      run: terraform fmt -recursive
     
      
    - name: Terraform Init
    
      run: terraform init
   

      

    - name: Terraform Validate
      
      run: terraform validate

    - name: Terraform Plan
      
      run: terraform plan -out=tfplan -input=false 
      

    - name: Terraform Apply
      
      run: terraform apply -input=false -auto-approve tfplan
     